// <auto-generated />
using Finnova.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Finnova.Repository.Migrations
{
    [DbContext(typeof(FinnovaDbContext))]
    [Migration("20260923140000_CreateOrganizationsAndUsers")]
    partial class CreateOrganizationsAndUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal. This is a hand-authored repair migration whose Up/Down use raw
            // SQL; EF applies that SQL directly during `database update` and never diffs this
            // intermediate target model (only the final FinnovaDbContextModelSnapshot is diffed).
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
